# Generated by Django 5.2.6 on 2025-09-29 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='graphics_processor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='os',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_resolution',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category'),
        ),
    ]
