# Generated by Django 5.2.6 on 2025-10-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_address_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertisements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
